#!/usr/bin/env bash

# Basic echomd CLI installer

executablePath() {
  local name=$1
  if [[ $(uname) =~ Darwin ]]; then
    if [ -d /usr/local/bin ]; then
      echo "/usr/local/bin/$name";
    else
      echo "/usr/bin/$name";
    fi
  else
    echo "$(dirname $(which echo))/$name";
  fi
}

curl -LO https://webreflection.github.io/echomd/echomd/echomd.pl
chmod a+x echomd.pl

if [[ $USER =~ ^root|admin$ ]]; then
  mv echomd.pl "$(executablePath 'echomd')"
else
  ./echomd.pl 'A *password* is *needed* to install echomd'
  sudo mv echomd.pl "$(executablePath 'echomd')"
fi

echomd "
# Success
 echomd has been #green(successfully) installed.
"
